#!/usr/bin/env python3
"""
generate_report.py — Post-exercise readiness report generator
GS-11 Lab: Produces structured test reports from scenario logs

Usage:
    python3 generate_report.py --scenario 01 --output reports/
    python3 generate_report.py --log reports/scenario-01-*.log
"""

import argparse
import glob
import os
import re
import sys
from datetime import datetime


def parse_log_file(log_path: str) -> dict:
    """Parse a scenario log file and extract key metrics."""
    metrics = {
        "scenario": "unknown",
        "start_time": None,
        "end_time": None,
        "detect_time_s": None,
        "recover_time_s": None,
        "total_duration_s": None,
        "events": [],
    }

    if not os.path.exists(log_path):
        print(f"[!] Log file not found: {log_path}")
        return metrics

    with open(log_path) as f:
        for line in f:
            line = line.strip()
            metrics["events"].append(line)

            # Extract scenario name
            if "SCENARIO:" in line:
                m = re.search(r"SCENARIO: (.+)", line)
                if m:
                    metrics["scenario"] = m.group(1)

            # Extract timing metrics
            if "Detection time:" in line:
                m = re.search(r"Detection time:\s+(\d+)s", line)
                if m:
                    metrics["detect_time_s"] = int(m.group(1))

            if "Recovery time:" in line:
                m = re.search(r"Recovery time:\s+(\d+)s", line)
                if m:
                    metrics["recover_time_s"] = int(m.group(1))

            if "Total duration:" in line:
                m = re.search(r"Total duration:\s+(\d+)s", line)
                if m:
                    metrics["total_duration_s"] = int(m.group(1))

    return metrics


def generate_markdown_report(metrics: dict, output_dir: str) -> str:
    """Generate a Markdown post-exercise report."""
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    report_path = os.path.join(output_dir, f"report-{timestamp}.md")

    detect_s = metrics.get("detect_time_s")
    recover_s = metrics.get("recover_time_s")
    total_s = metrics.get("total_duration_s")

    detect_str = f"{detect_s}s" if detect_s is not None else "Not measured"
    recover_str = f"{recover_s}s" if recover_s is not None else "Not measured"
    total_str = f"{total_s}s" if total_s is not None else "Not measured"

    # Determine pass/fail against targets
    detect_pass = detect_s is not None and detect_s <= 120   # 2 min target
    recover_pass = recover_s is not None and recover_s <= 900  # 15 min target

    report = f"""# Post-Exercise Readiness Report

**Scenario:** {metrics['scenario']}
**Generated:** {datetime.now().isoformat()}
**Operator:** {os.environ.get('USER', 'unknown')}

---

## Metrics Summary

| Metric | Measured | Target | Result |
|--------|----------|--------|--------|
| Time-to-Detect (MTTD) | {detect_str} | < 120s | {'✅ PASS' if detect_pass else '❌ FAIL'} |
| Time-to-Recover (MTTR) | {recover_str} | < 900s | {'✅ PASS' if recover_pass else '❌ FAIL'} |
| Total Exercise Duration | {total_str} | — | — |

---

## What Was Tested

- [ ] Fill in scenario objectives
- [ ] List systems involved
- [ ] Note any deviations from the runbook

## What Worked

- 

## What Failed / Needs Improvement

- 

## Corrective Actions

| # | Issue | Action | Owner | Due Date |
|---|-------|--------|-------|----------|
| 1 | | | | |

## Raw Event Timeline

```
{chr(10).join(metrics['events'][:50])}
{'... (truncated)' if len(metrics['events']) > 50 else ''}
```

---
*Generated by GS-11 EMCOMM Lab — generate_report.py*
"""

    with open(report_path, "w") as f:
        f.write(report)

    return report_path


def main():
    parser = argparse.ArgumentParser(description="GS-11 EMCOMM post-exercise report generator")
    parser.add_argument("--scenario", help="Scenario number (e.g., 01)")
    parser.add_argument("--log", help="Path to specific log file")
    parser.add_argument("--output", default="reports/", help="Output directory (default: reports/)")
    args = parser.parse_args()

    if args.log:
        log_path = args.log
    elif args.scenario:
        pattern = f"reports/scenario-{args.scenario}*.log"
        logs = sorted(glob.glob(pattern))
        if not logs:
            print(f"[!] No logs found matching: {pattern}")
            sys.exit(1)
        log_path = logs[-1]  # Most recent
        print(f"[+] Using log: {log_path}")
    else:
        print("[!] Provide --scenario or --log")
        parser.print_help()
        sys.exit(1)

    metrics = parse_log_file(log_path)
    report_path = generate_markdown_report(metrics, args.output)
    print(f"[+] Report generated: {report_path}")


if __name__ == "__main__":
    main()
