! FRR Configuration — R2 (OSPF Area 0)

frr version 9.1
frr defaults traditional
hostname r2
no ipv6 forwarding
!
interface eth1
 ip address 10.0.12.2/30
 ip ospf area 0
 ip ospf hello-interval 10
 ip ospf dead-interval 40
!
interface eth2
 ip address 10.0.23.1/30
 ip ospf area 1
!
interface eth3
 ip address 10.2.100.1/24
 ip ospf area 1
!
interface lo
 ip address 10.255.0.2/32
 ip ospf area 0
!
router ospf
 ospf router-id 10.255.0.2
 area 1 stub
 passive-interface eth3
 passive-interface lo
 log-adjacency-changes detail
!
line vty
!
